name: test - prepare-cluster

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

concurrency:
  group: test-prepare-cluster-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-helm:
    runs-on: ubuntu-latest
    env:
      WORDPRESS_CHART_VERSION: 22.2.8

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            **/package-lock.json

      - name: build
        run: make package-prepare-cluster

      - name: pull helm chart
        run: |
          helm pull oci://registry-1.docker.io/bitnamicharts/wordpress --version ${{ env.WORDPRESS_CHART_VERSION }}

      - name: test prepare-cluster
        id: prepare-cluster
        uses: replicatedhq/reliability-actions/prepare-cluster@main
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          app-slug: replicated-actions-ci # from the Replicated QA team
          chart: wordpress-${{ env.WORDPRESS_CHART_VERSION }}.tgz
          helm-chart-name: wordpress
          helm-run-preflights: false
          kubernetes-distribution: kind

      - name: remove cluster
        id: remove-cluster
        if: always()
        uses: replicatedhq/compatibility-actions/remove-cluster@v1
        continue-on-error: true # It could be that the cluster is already removed
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.prepare-cluster.outputs.cluster-id }}

  test-kots-install:
    runs-on: ubuntu-latest
    env:
      WORDPRESS_CHART_VERSION: 22.2.8

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            **/package-lock.json

      - name: build
        run: make package-prepare-cluster

      - name: test prepare-cluster
        id: prepare-cluster
        uses: replicatedhq/reliability-actions/prepare-cluster@main
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          app-slug: replicated-actions-ci # from the Replicated QA team
          yaml-dir: ./test/kots-install/yaml
          kubernetes-distribution: kind
          kots-config-values: |
            apiVersion: kots.io/v1beta1
            kind: ConfigValues
            metadata:
              name: nginx
            spec:
              values:
                api_token:
                  value: r8yWQ/cUeLVprKGKZb2gpE5IcQ0Tep1iaNwn7078
                example_default_value:
                  default: please change this value
                  value: testing
                hidden_text:
                  value: lPiIJL1RfL4v/YKzHfnx/9HyR2x4t5wnVxSLmzJlmf12HlqlyBoSfnvd0O+mftiT8h0+kumsBqc=
                readonly_text_left:
                  value: 8WIAQHZW_G
                show_text_inputs:
                  default: "0"
                  value: "1"

      - name: remove cluster
        id: remove-cluster
        if: always()
        uses: replicatedhq/compatibility-actions/remove-cluster@v1
        continue-on-error: true # It could be that the cluster is already removed
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.prepare-cluster.outputs.cluster-id }}
